fail_fast: true
default_language_version:
  ruby: 2.7.4
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  # - repo: local
  #   hooks:
  #     - id: rspec-tests
  #       name: Run Tests
  #       description: Ensures the unit tests still pass
  #       language: ruby
  #       entry: bundle exec rspec
  #     - id: rubocop-autocorrect
  #       name: RuboCop Autocorrect issues
  #       description: Ensures code hygiene
  #       entry: rubocop --require rubocop-rails --require rubocop-rspec -A
  #       language: ruby
