language: ruby

cache: bundler

rvm:
  - 2.7.4

env:
  - DB=pgsql

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rake

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database swapsea_test;' -U postgres
