dist: xenial

language: ruby

cache: bundler

rvm:
  - 3.1.2

env:
  - DB=pgsql

services:
  - postgresql
  - xvfb

script:
  - RAILS_ENV=test bundle exec rake db:test:load
  - RAILS_ENV=test bundle exec rake

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database swapsea_test;' -U postgres

addons:
  chrome: stable

before_install:
  -  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
